name: Test set 1

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setting up python

      uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"


      # checking obvious coding errors with flake 8
    - name: flake8 linting prpcess
      run: flake8 --count --select=E1,E9 --show-source --statistics ./src/fmi_pv_forecaster/*.py

