# This file contains automated tests triggers for github. The tests run lint which is a process of finding code style
# "errors" and actual python pytests.
name: Test set 1

on: [ push ]

jobs:
  flake8-lint:
    # code style checks, these are not too important
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: py-actions/flake8@v2
        with:
          ignore: "E265, E303, E501, W503, F824, E128, F841, E127, E126, E231"
          exclude: "testfile1.py, testfile2.py, tests/LEGACY_pv_forecast_test.py"
          max-line-length: "120"

  test-radiation-forecast:
    # testing if FMI radiation forecast bit works as expected
    runs-on: ubuntu-latest
    name: Testing FMI radiation forecasting functions
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          python -m pip install --upgrade pip
          pip install . pytest
      - run: pytest tests/radiation_forecasting_tests.py -s

  test-radiation-transposition:
    # testing if transposition functions work without obvious issues
    runs-on: ubuntu-latest
    name: Testing radiation transposition functions
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          python -m pip install --upgrade pip
          pip install . pytest
      - run: pytest tests/radiation_transposition_tests.py -s



  test-panel-reflection-equations:
    # testing if panel reflections are correct
    runs-on: ubuntu-latest
    name: Testing panel reflections
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          python -m pip install --upgrade pip
          pip install . pytest
      - run: pytest tests/reflection_estimation_tests.py -s

  test-module-temp-equation:
    # testing if module temperature equation works
    runs-on: ubuntu-latest
    name: Testing module temp equation
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          python -m pip install --upgrade pip
          pip install . pytest
      - run: pytest tests/panel_temperature_tests.py -s

  test-output-estimation:
    # testing if output estimation function works
    runs-on: ubuntu-latest
    name: Testing output estimation function
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          python -m pip install --upgrade pip
          pip install . pytest
      - run: pytest tests/output_estimation_tests.py -s

  test-forecasts:
    # testing if actual full forecasts works, or rather do not crash as their testing is really complex. Other tests
    # should have picked up failures if something major exists.
    runs-on: ubuntu-latest
    name: Testing full forecast functions, FMI and pvlib clearsky
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          python -m pip install --upgrade pip
          pip install . pytest
      - run: pytest tests/forecast_tests.py -s